
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Septy
 */
public class formkasir extends javax.swing.JFrame {

    public formkasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pilihan = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        noresi = new javax.swing.JTextField();
        jumlahhari = new javax.swing.JTextField();
        nopol = new javax.swing.JTextField();
        namapetugas = new javax.swing.JTextField();
        total = new javax.swing.JButton();
        tanggalkeluar = new com.toedter.calendar.JDateChooser();
        tanggalmasuk = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        totalbayar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        motor = new javax.swing.JRadioButton();
        mobil = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("DFGothic-EB", 1, 24)); // NOI18N
        jLabel1.setText("PARKIR SELALU AMAN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(260, 10, 280, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Biaya 3000/hari");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(340, 50, 210, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("=======================");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 50, 880, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 780, 100);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(null);

        jLabel4.setText("Total Bayar");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(420, 170, 100, 14);

        jLabel5.setText("No Resi");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 10, 70, 14);

        jLabel6.setText("No Polisi");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 60, 60, 14);

        jLabel7.setText("Jenis Kendaraan");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 110, 110, 14);

        jLabel8.setText("Tanggal Masuk");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(420, 10, 110, 20);

        jLabel9.setText("Tanggal Keluar");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(420, 60, 100, 20);
        jPanel2.add(noresi);
        noresi.setBounds(130, 10, 200, 30);
        jPanel2.add(jumlahhari);
        jumlahhari.setBounds(520, 110, 170, 30);
        jPanel2.add(nopol);
        nopol.setBounds(130, 60, 200, 30);
        jPanel2.add(namapetugas);
        namapetugas.setBounds(130, 160, 200, 30);

        total.setText("Total");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel2.add(total);
        total.setBounds(700, 160, 57, 30);
        jPanel2.add(tanggalkeluar);
        tanggalkeluar.setBounds(520, 60, 200, 30);
        jPanel2.add(tanggalmasuk);
        tanggalmasuk.setBounds(520, 10, 200, 30);

        jLabel11.setText("Jumlah Hari");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(420, 120, 90, 14);
        jPanel2.add(totalbayar);
        totalbayar.setBounds(520, 160, 170, 30);

        jLabel12.setText("Nama Petugas");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 160, 100, 14);

        motor.setBackground(new java.awt.Color(204, 255, 255));
        pilihan.add(motor);
        motor.setText("Motor");
        jPanel2.add(motor);
        motor.setBounds(130, 110, 70, 23);

        mobil.setBackground(new java.awt.Color(204, 255, 255));
        pilihan.add(mobil);
        mobil.setText("Mobil");
        jPanel2.add(mobil);
        mobil.setBounds(230, 110, 93, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 100, 780, 220);

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.setLayout(null);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel3.add(save);
        save.setBounds(50, 20, 73, 23);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel3.add(clear);
        clear.setBounds(200, 20, 70, 23);

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel3.add(delete);
        delete.setBounds(360, 20, 80, 23);

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel3.add(refresh);
        refresh.setBounds(670, 20, 80, 23);

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel3.add(print);
        print.setBounds(510, 20, 80, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 320, 790, 60);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setLayout(null);

        data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "noresi", "nopolisi", "jeniskendaraan", "namapetugas", "tanggalmasuk", "tanggalkeluar", "jumlahhari", "totalbayar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(data);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 760, 160);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 380, 780, 250);

        setSize(new java.awt.Dimension(797, 670));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
        int hari = Integer.parseInt(jumlahhari.getText().toString());
       
        int hasil = hari*3000;
        totalbayar.setText(""+hasil);
    }//GEN-LAST:event_totalActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String masuk = dateFormat.format(tanggalmasuk.getDate());
        String keluar = dateFormat.format(tanggalkeluar.getDate());
        String JK = "";
       
        String nor = noresi.getText();
        String nop = nopol.getText();
        String np = namapetugas.getText();
        String jh = jumlahhari.getText();
        String tb = totalbayar.getText();
        
        if (motor.isSelected()) {
            JK = "Motor";
        } else {
            JK = "Mobil";
        }
        if (noresi.getText().equals("") || 
           nopol.getText().equals("") ||
           JK.equals("") ||
           namapetugas.getText().equals("") ||
           masuk.equals("") ||
           keluar.equals("")||
           jumlahhari.getText().equals("") ||
           totalbayar.getText().equals("")){
            
            JOptionPane.showMessageDialog(this, "Harap Lengkai Data", "Error",
                    JOptionPane.WARNING_MESSAGE);
        }else{            
            String SQL ="INSERT INTO tb_transaksi (noresi,nopolisi,jeniskendaraan,namapetugas,tanggalmasuk,tanggalkeluar,jumlahhari,totalbayar)" 
                    + "VALUES('"
                    +noresi.getText()+"','"
                    +nopol.getText()+"','"
                    +JK+"',"
                    + "'"
                    +namapetugas.getText()+"','"
                    +masuk+"','"
                    +keluar+"','"
                    +jumlahhari.getText()+"','"
                    +totalbayar.getText()+")";
                    
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                 JOptionPane.showMessageDialog(this, "Data berhasil diupdate","Sukses", JOptionPane.INFORMATION_MESSAGE);
                 selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int baris = data.getSelectedRow();
        if (baris != -1){
            String NIS = data.getValueAt(baris,0).toString();
            String SQL = "DELETE FROM tb_transaksi WHERE noresi='"+noresi+"'";
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        noresi.setText("");
        nopol.setText("");
        pilihan.clearSelection();
        namapetugas.setText("");
        jumlahhari.setText("");
        totalbayar.setText("");
        tanggalmasuk.setDate(null);
        tanggalkeluar.setDate(null);
    }//GEN-LAST:event_clearActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}       ");
        try {
            data.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_printActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formkasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formkasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formkasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formkasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formkasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JTable data;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jumlahhari;
    private javax.swing.JRadioButton mobil;
    private javax.swing.JRadioButton motor;
    private javax.swing.JTextField namapetugas;
    private javax.swing.JTextField nopol;
    private javax.swing.JTextField noresi;
    private javax.swing.ButtonGroup pilihan;
    private javax.swing.JButton print;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private com.toedter.calendar.JDateChooser tanggalkeluar;
    private com.toedter.calendar.JDateChooser tanggalmasuk;
    private javax.swing.JButton total;
    private javax.swing.JTextField totalbayar;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"noresi","nopolisi","jeniskendaraan","namapetugas","tanggalmasuk","tanggalkeluar","jumlahhari","totalbayar"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_transaksi";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()) {
                String noresi = rs.getString(1);
                String nopolisi = rs.getString(2);
                String jeniskendaraan = "";
                if ("Motor".equals(rs.getString(3))){
                    jeniskendaraan = "Motor";
                } else {
                    jeniskendaraan = "Mobil";
                }
                String namapetugas = rs.getString(4);
                String tanggalmasuk = rs.getString(5);
                String tanggalkeluar = rs.getString(6);
                String jumlahhari = rs.getString(7);
                String totalbayar = rs.getString(8);
                String data[] = {noresi,nopolisi,jeniskendaraan,namapetugas,tanggalmasuk,tanggalkeluar,jumlahhari,totalbayar};
                dtm.addRow(data);
            }
        } catch (SQLException ex){
            Logger.getLogger(formkasir.class.getName()).log(Level.SEVERE, null, ex);
        }
        data.setModel(dtm);
    }
}
